#!/bin/sh

cap=$(cat /sys/class/power_supply/BAT0/capacity)
stat=$(cat /sys/class/power_supply/BAT0/status)

if [ "$cap" -le 20 ] && [ "$stat" != "Charging" ]; then
  if [ ! -f /tmp/notify_time ]; then
    notify "BATTERY LOW: $cap%" 10 &
  fi
fi

[ "$stat" = "Charging" ] && echo "󱐋 $cap%" || echo "󰂂 $cap%"
