#!/bin/bash

temp=$(sensors | rg -oP 'Package id 0:.*?\+\K[0-9.]+' | head -n 1)
[ -z "$temp" ] && { echo " ERR"; exit 1; }

temp_int=${temp%.*}

NOTIF_FILE="${XDG_RUNTIME_DIR:-/tmp}/notify"

if [ "$temp_int" -ge 75 ]; then
    ICON="🔥"

    if [ ! -s "$NOTIF_FILE" ]; then
        notify "HOT: ${temp_int}°C" 10 &
    fi
else
    ICON=""
fi

echo "$ICON ${temp_int}°C"
