#!/bin/sh

status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null)

if [ $? -ne 0 ]; then
	echo "󰝟 No Sink"
else
	vol=$(echo "$status" | awk '{print $2 * 100}')
	[ "${status#*\[MUTED]}" != "$status" ] && echo "󰝟 Mute" || echo "󰕾 ${vol%.*}%"
fi
