#!/bin/bash

DIR="$HOME/pics/ss"
FILE="$DIR/$(date +'%Y-%m-%d_%H-%M-%S').png"

[[ ! -d "$DIR" ]] && mkdir -p "$DIR"

GEOM=$(slurp) || exit 1

grim -g "$GEOM" "$FILE"

if [[ -f "$FILE" ]]; then
    wl-copy < "$FILE"
    notify "$FILE saved and copied to clipboard"
fi
