#!/bin/bash

INTERFACE="wlan0"

iwctl station "$INTERFACE" scan &

GET_SSIDS="iwctl station $INTERFACE"
GET_SSIDS+=" get-networks | sed 's/\x1b\[[0-9;]*m//g' | rg '(psk|open|8021x)' | sed 's/^[^[:space:]]*//' | rg -oP '^.{0,32}' | sed 's/[[:space:]]*$//'"

SELECTED_SSID=$(eval "$GET_SSIDS" | fzf \
  --prompt="󰖩 Select WiFi: " \
  --reverse \
  --no-info \
  --header "Ctrl-R: Refresh" \
  --bind "start:reload(sleep 1 && $GET_SSIDS)" \
  --bind "focus:reload($GET_SSIDS)" \
  --bind "ctrl-r:reload($GET_SSIDS)"
)

[ -z "$SELECTED_SSID" ] && exit 0

echo "Connecting to $SELECTED_SSID..."

if ! iwctl station "$INTERFACE" connect "$SELECTED_SSID"; then
  read -rs -p "Enter Password for $SELECTED_SSID: " PASS
  echo ""

  if [ -n "$PASS" ]; then
    printf "%s\n" "$PASS" | iwctl station "$INTERFACE" connect "$SELECTED_SSID"
  fi
fi
