#!/bin/bash

if [ "$1" = "--preview" ]; then
  
  DATA="$2"
  PREVIEW_TMP="/dev/shm/clip_prev_$USER"
  echo "$DATA" | cliphist decode > "$PREVIEW_TMP" 2>/dev/null
  FILE_TYPE=$(file -b --mime-type "$PREVIEW_TMP")

  case "$FILE_TYPE" in
    image/*)
      chafa -s 55x55 --format=sixels "$PREVIEW_TMP" ;;
    text/*|application/x-empty)
      head -n 30 "$PREVIEW_TMP" ;;
    *)
      echo "Format: $FILE_TYPE"
      strings "$PREVIEW_TMP" | head -n 10 | cut -c 1-100 ;;
  esac
  exit 0
fi

selected=$(cliphist list | fzf \
  --no-info \
  --no-scrollbar \
  --prompt="󰅌 Clipboard: " \
  --preview="$0 --preview {}" \
  --preview-window=right:50%:wrap \
  --layout=reverse)

if [ -n "$selected" ]; then
  echo "$selected" | cliphist decode | wl-copy
fi
