#!/bin/bash

SOCKET="/tmp/mpv-music.sock"

if [ "$1" == "--remote" ]; then
  printf "%s\n" "$2" | socat - "$SOCKET" >/dev/null 2>&1
  exit 0
fi

play_it() {
  v_id="${1##* -- }"
  ! pgrep -x "mpv" > /dev/null && rm -f "$SOCKET"
  if [ -S "$SOCKET" ]; then
    printf "loadfile https://www.youtube.com/watch?v=$v_id&list=RD$v_id replace\n" | \
      socat - "$SOCKET" >/dev/null 2>&1
  else
    nohup mpv --no-video \
        --input-ipc-server="$SOCKET" \
        --ytdl-format="bestaudio/best" \
        --ytdl-raw-options="yes-playlist=" \
        "https://www.youtube.com/watch?v=$v_id&list=RD$v_id" > /dev/null 2>&1 &
  fi
}

while true; do
  query=$(fzf --reverse --print-query --no-info \
              --prompt="󰎈 Search: " \
              --header "CTRL-P: Pause | CTRL-Q: Quit | CTRL-B: Bwd | CTRL-N: Fwd" \
              --bind "ctrl-p:execute($0 --remote 'cycle pause')" \
              --bind "ctrl-n:execute($0 --remote 'seek 10')" \
              --bind "ctrl-b:execute($0 --remote 'seek -10')" \
              --bind "ctrl-q:execute($0 --remote 'quit')+abort" < /dev/null)
  [ -z "$query" ] && exit 0
  results=$(yt-dlp --quiet "ytsearch10:$query" \
              --get-title --get-id | sed 'N;s/\n/ -- /')
  [ -z "$results" ] && continue
  selected=$(echo "$results" | fzf --reverse --no-info --prompt="󰝚 Play: ")
  [ -n "$selected" ] && play_it "$selected"
done
